# Generated by Django 3.1.7 on 2021-04-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_newslettersubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'verbose_name': 'Newsletter Subscription'},
        ),
    ]
